Feat/zapper v3
oraichain/oraiswap-frontend pull request #965
Opened 2024-09-25 10:51 UTC by vuonghuuhung

2024-09-25 10:56 UTC, haunv3 approved these changes

2024-09-26 07:23 UTC, haunv3 approved these changes

2024-09-26 07:30 UTC, haunv3 submitted a review, later dismissed

2024-09-26 07:38 UTC, trungbach requested changes

2024-09-26 07:38 UTC, trungbach commented on src/pages/Pool-V3/components/PoolList/index.tsx
>          if (!poolList?.length) return;
Can you pls remove debug logs? @vuonghuuhung

2024-09-26 07:38 UTC, trungbach commented on src/pages/Pool-V3/components/PoolList/index.tsx
> +        // console.log('prevPoolListRef.current', prevPoolListRef.current);
remove it also

2024-09-26 07:38 UTC, trungbach commented on src/pages/Pool-V3/components/PriceRangePlot/utils.ts
> +  const testPrice = calcPrice(isXtoY ? minTick : maxTick, isXtoY, xDecimal, yDecimal);
Where do you use this variable mate? @vuonghuuhung

2024-09-26 07:38 UTC, trungbach commented on src/pages/Pool-V3/components/ZapOutForm/index.tsx
> +    } catch (error) {}
i think in this catch block we need at least console error for debug?

2024-09-26 08:05 UTC, haunv3 approved these changes

2024-09-26 08:08 UTC, trungbach approved these changes
LGTM. Good job mate.

2024-09-26 08:53 UTC, haunv3 approved these changes

2024-09-26 08:58 UTC, quangdz1704 approved these changes

2024-09-26 09:01 UTC, merged